apiVersion: v1
kind: Pod                          
metadata:
        name: client
        labels:
                app: client
spec:
        containers:
                - image: thelusina/sentiment-analysis-client 
                  name: client
                  ports:
                          - containerPort: 80
