apiVersion: extensions/v1beta1
kind: Deployment
metadata:
        name: client-deployment
spec:
        replicas: 2
        minReadySeconds: 15
        strategy:
                type: RollingUpdate
                rollingUpdate:
                        maxUnavailable: 1
                        maxSurge: 1
        template:
                metadata:
                        labels:
                                app: client
                spec:
                        containers:
                                - image: thelusina/sentiment-analysis-client
                                  imagePullPolicy: Always
                                  name: client
                                  ports:
                                          - containerPort: 80

