apiVersion: v1
kind: Pod                          
metadata:
        name: sa-client
        labels:
                app: sa-client
spec:
        containers:
                - image: thelusina/sentiment-analysis-client 
                  name: sa-client
                  ports:
                          - containerPort: 80
