version: "3.0"

services:
  client:
    restart: always
    build: ./client
    ports:
      - "3000:80"
    expose:
      - "3000"
    depends_on:
      - webapp

  webapp:
    restart: always
    build: ./webapp
    ports:
      - "8080:8080"
    expose:
      - "8080"
    command: java -server -Xms4g -Xmx4g -XX:+UseG1GC -XX:MaxGCPauseMillis=100 -XX:+UseStringDeduplication -jar webapp.jar
    depends_on:
     - logic

  logic:
    restart: always
    build: ./logic
    ports:
      - "5000:5000"
    expose:
      - "5000"
    command: python sentiment_analysis.py
