version: "3.0"

services:
  client:
    restart: always
    build: ./client
    ports:
      - "3000:80"
    expose:
      - "3000"
    volumes:
      - /usr/share/nginx/html/
    depends_on:
      - server

  webapp:
    restart: always
    build: ./webapp
    ports:
      - "8080:8080"
    expose:
      - "8080"
    volumes:
     - /usr/src/app/app/static
    command: python manage.py runserver
    depends_on:
     - logic

  logic:
    restart: always
    build: ./logic
    ports:
      - "5000:5000"
    expose:
      - "5000"
    command: python manage.py runserver


