apiVersion: extensions/v1beta1
kind: Service
metadata:
        name: webapp-load-balancer
spec:
        type: LoadBalancer
        ports:
                - port: 80
                  protocol: TCP
                  targetPort: 8080
        selector:
                app: webapp
